config/routes.rb
# This code is intended to be used **for training purposes only**.
Rails.application.routes.draw do

  get 'login/index'

  get 'users/me'

  get 'users/home'

  post 'login/refresh'

  get 'login/callback'

  get 'login/revoke'

  root 'login#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# This code is intended to be used **for training purposes only**.
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# This code is intended to be used **for training purposes only**.
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  add_flash_types :danger, :success

end

app/controllers/login_controller.rb
# This code is intended to be used **for training purposes only**.
require 'json'
require 'rest-client'
require 'date'

class LoginController < ApplicationController

  def callback
    # Grab the value of the authorization code returned by Procore
    @authorization_code = params["code"]

    # Populate the request body with the defined parameters from the docs
    # Reference documentation: https://developers.procore.com/reference/authentication
    request = {
      grant_type: "authorization_code",
      client_id: ENV['CLIENT_ID'],
      client_secret: ENV['CLIENT_SECRET'],
      code: @authorization_code,
      redirect_uri: ENV['REDIRECT_URI']
    }

    # Send a request for an access token to Procore and store the response in a session variable
    response = RestClient.post(ENV['OAUTH_URL'] +'/oauth/token', request.to_json, { content_type: :json, accept: :json })
    session[:oauth_response] = JSON.parse(response)

    # Redirect the user's browser to the intended home page
    redirect_to users_home_path, success: "You have successfully obtained an access token!"

    rescue RestClient::ExceptionWithResponse
      if session[:oauth_response]
        redirect_to users_home_path, danger: "Something went wrong. Please refresh your access token and try again."
      else
        redirect_to login_index_path, danger: "Something went wrong. Please try again."
      end
    end


  def refresh
    # Populate the request body with the defined parameters from the docs
    # Reference documentation: https://developers.procore.com/reference/authentication
    request = {
      grant_type: "refresh_token",
      client_id: ENV['CLIENT_ID'],
      client_secret: ENV['CLIENT_SECRET'],
      refresh_token: session[:oauth_response]['refresh_token'],
      redirect_uri: ENV['REDIRECT_URI']
    }

    # Send a request for an access token to Procore and store the response in a session variable
    response = RestClient.post(ENV['OAUTH_URL'] + '/oauth/token', request.to_json, { content_type: :json, accept: :json })
    session[:oauth_response] = JSON.parse(response)

    # Redirect the user's browser to the intended home page
    redirect_to users_home_path, success: "You have successfully refreshed your access token!"

    rescue RestClient::ExceptionWithResponse
      if session[:oauth_response]
        redirect_to users_home_path, danger: "Something went wrong. Please refresh your access token and try again."
      else
        redirect_to login_index_path, danger: "Something went wrong. Please try again."
      end
    end

  def revoke
    # Populate the request body with the defined parameters from the docs
    # https://developers.procore.com/reference/authentication#revoke-token
    request = {
      client_id: ENV['CLIENT_ID'],
      client_secret: ENV['CLIENT_SECRET'],
      token: session[:oauth_response]['access_token']
    }
    # Send a request to revoke the access token to Procore and return to the Sign In page.
    # Note that in the production environment, this request uses the BASE_URL (https://api.procore.com) to revoke the token.
    response = RestClient.post(ENV['BASE_URL'] + '/oauth/revoke', request.to_json)
    # Deletes current session to clear out session variables
    reset_session
    # Redirects user back to the login page
    redirect_to login_index_path

    rescue RestClient::ExceptionWithResponse
      if session[:oauth_response]
        redirect_to users_home_path, danger: "Something went wrong. Please refresh your access token and try again."
      else
        redirect_to login_index_path, danger: "Something went wrong. Please try again."
      end
  end
end

app/controllers/users_controller.rb
# This code is intended to be used **for training purposes only**.
class UsersController < ApplicationController

  def me
    # Send a request to the Show User Info endpoint
    # Reference documentation: https://developers.procore.com/reference/me
    get_me = RestClient.get(ENV['BASE_URL'] +'/vapid/me',
            { Authorization: "Bearer #{session[:oauth_response]['access_token']}" })

    # Store the parsed response in an instance variable
    @me = JSON.parse(get_me)

    rescue RestClient::ExceptionWithResponse
      if session[:oauth_response]
        redirect_to users_home_path, danger: "Something went wrong. Please check or refresh your access token and try again."
      else
        redirect_to login_index_path, danger: "Something went wrong. Please try again."
      end
  end

  def home
    # Fetch the access token from the previously-set session variable and store
    # the value in an instance variable
    @access_token = session[:oauth_response]['access_token']

    # Fetch the 'created_at' value from the session variable, prettify it, and
    # store the value in an instance variable
    created_at = session[:oauth_response]['created_at']
    @pretty_created_at = Time.at(created_at).asctime

    # Fetch the 'expires_in' value from the session variable, add it to the
    # 'created_at' value to find the time at which the access token will expire,
    # and store the new 'expires_at' value in an instance variable
    expires_in = session[:oauth_response]['expires_in']
    expires_at = expires_in + created_at
    @pretty_expires_at = Time.at(expires_at).asctime

    # Fetch the access token from the session variable and store the value in
    # an instance variable
    @refresh_token = session[:oauth_response]['refresh_token']

    rescue RestClient::ExceptionWithResponse
      if session[:oauth_response]
        redirect_to users_home_path, danger: "Something went wrong. Please refresh your access token and try again."
      else
        redirect_to login_index_path, danger: "Something went wrong. Please try again."
    end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!-- This code is intended to be used **for training purposes only**. -->
<!DOCTYPE html>
<html>
  <head>
    <title>Sample ROR App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
        <ul class="nav nav-tabs">
          <% if session[:oauth_response] %>
            <li><%= link_to "Home", users_home_path %></li>
            <li><%= link_to "Sign Out", login_revoke_path %></li>
          <% else %>
            <li><%= link_to "Sign In", login_index_path %></li>
          <% end %>
        </ul>

      <%= yield %>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<!-- This code is intended to be used **for training purposes only**. -->
<div>
  <%= link_to 'Sign In To Procore', "#{ENV['OAUTH_URL']}/oauth/authorize?client_id=#{ENV['CLIENT_ID']}&response_type=code&redirect_uri=#{ENV['REDIRECT_URI']}", :class => "button"%>
</div>

app/views/users/home.html.erb
<!-- This code is intended to be used **for training purposes only**. -->
<head>
  <% flash.each do |key, value| %>
    <div class='alert alert-<%= key %>' >
      <%= value %>
      </div>
  <% end %>
</head>

<table>
  <tr>
    <th>Access Token</th>
    <th>Created At</th>
    <th>Expires At</th>
    <th>Refresh Token
    </th>
  </tr>
  </tr>
    <td><%= @access_token[0..4] + "..." + @access_token.split(//).last(5).join%></td>
    <td><%= @pretty_created_at %></td>
    <td><%= @pretty_expires_at %></td>
    <td><%= @refresh_token[0..4] + "..." + @refresh_token.split(//).last(5).join %></td>
  </tr>
</table>

<div class="me-button">
  <%= link_to "Show User Information", users_me_path, method: :get, class: :button %>
</div>

<div class="refresh-button">
  <%= link_to "Refresh Your Access Token", login_refresh_path, method: :post, class: :button%>
</div>

<div class="revoke-button">
  <%= link_to "Revoke Your Access Token", login_revoke_path, method: :get, class: :button%>
</div>

app/views/users/me.html.erb
<!-- This code is intended to be used **for training purposes only**. -->
<table>
    <tr>
      <th>User ID</th>
      <th>User Email</th>
    </tr>
  <div>
    <tr>
      <td><%= @me['id'] %></td>
      <td><%= @me['login']%></td>
    </tr>
</table>

<div class="home-button">
  <%= link_to "Go Back to Home Page", users_home_path, method: :get, class: :button %>
</div>